# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-22 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='org',
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='gender',
            field=models.CharField(choices=[('boy', '男'), ('girl', '女')], default='boy', max_length=10, verbose_name='讲师性别'),
        ),
    ]
